### ISSUE TITLE
Request: Allowing an option to explicitly mark posts as drafts.

### ISSUE THREAD

**Issue by AniketSK** [shooontan/gatsby-plugin-draft#2]
First of all thanks for such a great and necessary plugin! I have a use case which I'd like to propose and add code for myself or you could do it if you'd want to.

The problem:
Right now I need to set a future date for a post if I want it to be a draft.
Perhaps I'm not sure when I want to publish it and if I forget, it's going to be slipped into production when I intended to publish a different article.

Proposed solution:
Allow declaring posts drafts explicitly, such as with draft:true and having that be respected so it won't be published.
This could be an option in the plugin options.

If you think this is a good idea, I could figure out how to add this option and make a pull request. Thanks!

**Comment by shooontan** [comment]
I released `0.0.4` version with `publishDraft` option.
