### ISSUE TITLE
[Bug] Drafts still appear in the listing of the topics

### ISSUE THREAD

**Issue by AniketSK** [shooontan/gatsby-plugin-draft#5]
So I was trying out how this works, and I noticed that the draft article appears in the list:
![Screenshot_20190418_121438](https://user-images.githubusercontent.com/4136334/56357533-ea651e80-61d3-11e9-8264-4b2a5187fa45.png)

**Even though the link doesn't work:**
![Screenshot_20190418_121453](https://user-images.githubusercontent.com/4136334/56357569-04066600-61d4-11e9-869b-aa7de46cb50b.png)

I've uploaded my code [here](https://bitbucket.org/AniketSK/op.aniketkadam.com/branch/drafts/theranos-notes) if you'd like to look through any part of it.
For convenience, here's:
1. [index.md of the draft file](https://bitbucket.org/AniketSK/op.aniketkadam.com/src/a4bb1af8ee6a478af21d054c958e51d2b574a26c/src/pages/theranos-similarities/index.md?at=drafts%2Ftheranos-notes)
2. My [gatsby-config.js](https://bitbucket.org/AniketSK/op.aniketkadam.com/src/a4bb1af8ee6a478af21d054c958e51d2b574a26c/gatsby-config.js?at=drafts%2Ftheranos-notes)
3. My [gatsby-node.js](https://bitbucket.org/AniketSK/op.aniketkadam.com/src/a4bb1af8ee6a478af21d054c958e51d2b574a26c/gatsby-node.js?at=drafts%2Ftheranos-notes)

I tried this out with `gatsby build && gatsby serve`

**Comment by shooontan** [comment]
Please add filter query like following in [here](https://bitbucket.org/AniketSK/op.aniketkadam.com/src/a4bb1af8ee6a478af21d054c958e51d2b574a26c/src/pages/index.js?at=drafts%2Ftheranos-notes&fileviewer=file-view-default#index.js-60).

```
    allMarkdownRemark(
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { fields: { draft: { eq: false } } }
    ) {
```

**Comment by AniketSK** [comment]
Thanks! That fixes it, however this isn't mentioned in the Readme, only the gatsby-node.js modification is, and might be missed by others. Perhaps worth adding there too?

**Comment by tkrempser** [comment]
I had the same issue, this info should be added to the README.md file.

**Comment by zapatran** [comment]
The same issue here it should be added to the README.md

**Comment by shooontan** [comment]
I updated README.md.
thanks!
